[package]
name = "moecs_macros"
description = "Macros for the MOECS ECS engine."
version = "0.1.0"

edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
